const mongoose = require('mongoose'); 

const Schema = mongoose.Schema;

const userSchema = new Schema({
    // not sure if I need to specify because mongodb does this userId: autogenerated, 
    username: {
        type: String, 
        required: true, 
        unique: true
    }, 
    password: {
        type: String, 
        required: true, 
    }, 
    email: String, 
    phone: Number
});

const User = mongoose.model('User', userSchema); 
module.exports = User;